<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9979feff-f353-4c62-9957-8b87b19d6fd4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="GameStoreApiController/" />
    <Folder Include="Middleware/" />
    <Folder Include="Model/" />
    <Folder Include="Service/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.9" />
  </ItemGroup>

</Project>
